### ISSUE TITLE
Via Enclosure Errors

### ISSUE THREAD

**Issue by yrrapt** [laurentc2/SKY130_for_KLayout#1]
Hey,

I've been trying out the DRC files and it's looking good. I did notice one odd thing with vias though.

I think there is no error as the via is totally enclosed by metal 1 and metal 2 but an error is still reported. Maybe you have some ideas of where the issue lies?

I've included the original in a zip file you should be able to open.

![image](https://user-images.githubusercontent.com/20978130/96766080-d6a70380-13da-11eb-99e9-ee109fdad213.png)

![image](https://user-images.githubusercontent.com/20978130/96766176-fc340d00-13da-11eb-8d42-1a092004a22b.png)

[test.gds.zip](https://github.com/laurentc2/SKY130_for_KLayout/files/5418006/test.gds.zip)

**Comment by laurentc2** [comment]
I solved it. It should have sized() instead of size() in the huge_metal statement.

**Comment by yrrapt** [comment]
Awesome. Thanks for the quick reply and fix.
