### ISSUE TITLE
Document KLayout rule status?

### ISSUE THREAD

**Issue by mithro** [laurentc2/SKY130_for_KLayout#2]
Hi!

This looks like cool work!

We have a spreadsheet at https://docs.google.com/spreadsheets/d/1oL6ldkQdLu-4FEQE0lX6BcgbqzYfNnd1XA8vERe0vpE/edit#gid=530166750 (see the "Magic DRC rule status" sheet) which documents the status of DRC checks in Magic. It would be awesome to also have the KLayout column tracking your status, are you interested in helping with that?

Tim '@mithro' Ansell

**Comment by mithro** [comment]
It would also be awesome to develop some minimal GDS "test cases" which demonstrate each of the rules too.

**Comment by laurentc2** [comment]
I sent you the spreadsheet on SKY130 DRC checks in KLayout by email.
I unfortunately do not have GDS "test cases", but if you one for MAGIC, it will great for me to try it under KLayout.

Laurent
