### ISSUE TITLE
Sky130 Slack Discussion

### ISSUE THREAD

**Issue by yrrapt** [laurentc2/SKY130_for_KLayout#3]
Hi,

This is not the ideal method to communicate this but I can't seem to find a message user function.

There's some discussion over on the Skywater Slack #klayout channel about integrating your great work into the core distributed PDK. If you're interested, it would be great for you to join the discussion. The link is:
https://invite.skywater.tools/

I can delete this issue afterwards as it's not an actual issue with the tools.

Cheers,
Thomas

**Comment by laurentc2** [comment]
I have no google account to subscribe on slack.

BRgds,
Laurent

**Comment by mithro** [comment]
FYI - Slack doesn't require a Google account. Https://join.skywater.tools let's you send an invite to any email address.
