### ISSUE TITLE
P- Poly Resistors

### ISSUE THREAD

**Issue by yrrapt** [laurentc2/SKY130_for_KLayout#4]
I am experiencing a number of errors with P- poly resistors that are generated in Magic with the sky130A generators.

These issues seems to be caused by the precision resistors not being correctly detected and applying the correct rules.

I have attached and example GDS to demonstrate this.
[res.gds.zip](https://github.com/laurentc2/SKY130_for_KLayout/files/5469107/res.gds.zip)

**Comment by laurentc2** [comment]
Thank you for the test case ! I solve it.
