### ISSUE TITLE
skywater drc using sky130A.lydrc not catching poly-to-poly spacing drc violations

### ISSUE THREAD

**Issue by BoarensteinBoar** [laurentc2/SKY130_for_KLayout#8]
Hi,

For some reason, even when I deliberately make the poly to poly spacing in klayout to be under 0.21um ( i tried 0.1um and 0.05um),
the drc file (sky130A.lydrc) does not catch it. I tried doing this in magic, and the drc was caught immediately. Do you know what could be the issue? 

Thanks

**Comment by laurentc2** [comment]
I change 'isolated' checks to 'space' checks : it catch all cases, while isolated does not catch the notch (U shapes errors)

**Comment by BoarensteinBoar** [comment]
Hi Laurent, thanks for the quick response. I was able to fix it by changing feol = false to true in the .lydrc file. I am a newbie, so I did not know what FEOL meant at first.
